modLoader="javafml"
loaderVersion="[34,)"
license= "GNU LESSER GENERAL PUBLIC LICENSE"
licenseURL= "https://github.com/LeoBeliik/NoNetherFog/blob/master/LICENSE.txt"
issueTrackerURL="https://github.com/LeoBeliik/NoNetherFog/issues"
[[mods]]
modId="nonetherfog"
version="${file.jarVersion}"
displayName="No Nether Fog"
displayURL="https://www.curseforge.com/minecraft/mc-mods/no-nether-fog"
authors="LeoBeliik"
logoFile="nonf_icon.png"
description='''
This mod disables the fog in the nether.
It also adds a zoom key.
'''
[[dependencies.nonetherfog]]
modId="forge"
mandatory=true
versionRange="[34,)"
ordering="NONE"
side="BOTH"
[[dependencies.nonetherfog]]
modId="minecraft"
mandatory=true
versionRange="[1.16.3)"
ordering="NONE"
side="BOTH"